package mirrors_data

// MirrorList is list of debian mirror sites
var MirrorList_CentOS = []string{
	"http://us.mirror.nsec.pt/centos/","http://mirror.retentionrange.co.bw/centOS/",
	"http://centos.mirror.liquidtelecom.com/","http://mirror.marwan.ma/centos/",
	"http://mirror.cambo.host/centos/","http://mirror.myfahim.com/centos/",
	"http://mirrors.aliyun.com/centos/","http://mirrors.nju.edu.cn/centos/",
	"http://centos.01link.hk/","http://centos.excellmedia.net/",
	"http://centos.mirror.snu.edu.in/centos/","http://mirror.buana.web.id/centos/",
	"http://mirror.biznetgio.com/centos/","http://mirror.telkomuniversity.ac.id/centos/",
	"http://ftp.iij.ad.jp/pub/linux/centos/","http://ossm.utm.my/centos/",
	"http://ftp.nara.wide.ad.jp/pub/Linux/centos/","http://centos.gbnetwork.my/centos/",
	"http://download.nus.edu.sg/mirror/centos/","http://mirror.nus.edu.sg/centos/",
	"http://mirror.anigil.com/CentOS/", "http://ftp.kaist.ac.kr/CentOS/",
	"http://mirror.navercorp.com/centos/", "http://mirror01.idc.hinet.net/centos/",
	"http://ftp.stu.edu.tw/Linux/CentOS/" ,"http://ftp.ksu.edu.tw/pub/CentOS/",
	"http://mirror.megafon.tj/centos/","http://mirrors.bangmod.cloud/centos/",
	"http://mirror.kku.ac.th/centos/","http://mirrors.psu.ac.th/pub/centos/",
	"http://mirrors.inet.vn/centos/","http://mirror.horizon.vn/centos/",
	"http://mirrors.vhost.vn/centos/","http://centos-canada.altinsoft.net/",
	"http://centos-canada.vdssunucu.com.tr/","https://mirror.esecuredata.com/centos/",
	"http://mirror.it.ubc.ca/centos/","http://centos.mirrors.arminco.com/",
	"http://centos.anexia.at/centos/","http://centos.cu.be/",
	"http://mirror.datacenter.by/pub/CentOS/","http://mirror.yer.az/CentOS/",
	"http://centos.mirror.ba/","http://centos.telecoms.bg/","http://mirror.centos.plus.hr/centos/",
	"http://mirror.cs.ucy.ac.cy/centos/","http://ftp.sh.cvut.cz/centos/",
	"http://mirror.fysik.dtu.dk/linux/centos/","http://mirror.cspacehostings.com/centos/",
	"http://ftp.pasteur.fr/mirrors/CentOS/","http://centos.mirror.ate.info/",
	"http://ge.mirror.cloud9.ge/centos/","http://de.mirrors.clouvider.net/CentOS/",
	"http://linux.darkpenguin.net/distros/CentOS/","http://ftp.rrzn.uni-hannover.de/centos/",
	"http://ftp.cc.uoc.gr/mirrors/linux/centos/","http://mirror.niif.hu/centos/",
	"http://centos.hysing.is/","http://centos.mirror.garr.it/centos/",
	"http://mirrors.prometeus.net/centos/","http://centos.koyanet.lv/centos/",
	"http://centos.linux.edu.lv/","http://mirror.cherryservers.com/centos/",
	"http://mirror.dclux.com/centos/","http://repo.fedora.md/centos/",
	"http://nl.mirrors.clouvider.net/CentOS/","http://mirror.dataone.nl/centos/",
	"http://mirror.oxilion.nl/centos/","http://linux.cs.uu.nl/centos/",
	"http://centos2.hti.pl/","http://ftp.uninett.no/centos/",
	"http://ftp.man.szczecin.pl/pub/Linux/centos/","http://mirrors.pt/centos/",
	"http://ftp.dei.uc.pt/pub/linux/CentOS/","http://mirrors.chroot.ro/centos/",
	"http://mirrors.primetelecom.ro/centos/","http://centos.mirrors.telekom.ro/centos/",
	"http://mirrors.uav.ro/centos/","http://mirror.truenetwork.ru/centos/",
	"http://mirror.corbina.net/pub/Linux/centos/","http://mirrors.powernet.com.ru/centos/",
	"http://mirror.etf.bg.ac.rs/centos/","http://tux.rainside.sk/centos/",
	"http://mirror.airenetworks.es/CentOS/","https://ftp.cica.es/CentOS/",

}

